src/models/companies/views.py
from flask import Blueprint, request, render_template, redirect, url_for

from src.models.companies.company import Company


import src.models.users.decorators as user_decorators


__author__="Kunj"

company_blueprint = Blueprint('companies',__name__)

@company_blueprint.route('/new',methods=['GET','POST'])
@user_decorators.requires_login
def index():
    companies = Company.get_company()
    if len(companies) == 0:
        if request.method=='POST':
            name = request.form.get('name')
            email = request.form.get('email')
            gstin = request.form.get('gstin')
            address = request.form.get('address')
            city = request.form.get('city')
            pincode = request.form.get('pincode')
            state = request.form.get('state')
            country = request.form.get('country')
            bank_name = request.form.get('bank_name')
            branch = request.form.get('branch')
            account_number = request.form.get('account_number')
            ifsc = request.form.get('ifsc')

            company = Company(name, gstin, address, city, state,pincode,email,bank_name,branch,ifsc,account_number)
            company.save_to_mongo()

            return redirect(url_for('users.index'))

        return render_template("company/add_company.jinja2",company_page=True)
    else:
        if request.method == 'POST':
            name = request.form.get('name')
            email = request.form.get('email')
            gstin = request.form.get('gstin')
            address = request.form.get('address')
            city = request.form.get('city')
            pincode = request.form.get('pincode')
            state = request.form.get('state')
            country = request.form.get('country')
            bank_name = request.form.get('bank_name')
            branch = request.form.get('branch')
            account_number = request.form.get('account_number')
            ifsc = request.form.get('ifsc')
            print(state)
            company_edit = Company(name, gstin, address, city, state,pincode,email,bank_name,branch,ifsc,account_number,_id=companies[0]._id)
            company_edit.save_to_mongo()

            return redirect(url_for('users.index'))
        return render_template("company/edit_company.jinja2",company = companies[0], company_page = True)

src/models/items/views.py
from flask import Blueprint, request, render_template, jsonify, redirect, url_for, session

from src.models.invoices.invoice import Invoice
from src.models.items.item_company import Item_company
from src.models.items.item import Item
from src.models.items.type import Type

import src.models.users.decorators as user_decorators


__author__="Kunj"

item_blueprint = Blueprint('items',__name__)

@item_blueprint.route('/')
@user_decorators.requires_login
def index():
    print(session)
    return render_template("items/item_list.jinja2",datatable_page=True,item_list_page=True)

@item_blueprint.route('/new',methods=['POST', 'GET'])
@user_decorators.requires_login
def new_item():
    if request.method == 'POST':
        print("POST")
        model_name = request.form.get('model_name')
        x = request.form.get('company_name')
        company = request.form.get('add_new_company')
        hsn_code = request.form.get('hsn_code')
        type = request.form.get('add_new_type')
        y = request.form.get('type')

        tax = request.form.get('tax')
        price = request.form.get('price')
        if company == None:
            company = x
        if type == None:
            type = y
        #print(model_name,x,company,hsn_code,type,y,tax,price)
        item = Item(hsn_code,company,model_name,type,tax,price)
        item.save_to_mongo()
        return redirect(url_for('.index'))
        #return render_template("KK")
    companies = Item_company.get_all_companies()
    types = Type.get_all_types()
    return render_template('items/new_item.jinja2',companies=companies,types=types,new_item_page=True)


@item_blueprint.route('/index_get_data')
@user_decorators.requires_login
def item_data():
    #Assume data comes from somewhere else
    data = {}
    data["data"] = Item.get_data_for_list()
    return jsonify(data)

@item_blueprint.route('/delete/<string:item_id>')
@user_decorators.requires_login
def delete_item(item_id):
    x = Invoice.delete_item_possible(item_id)
    if x==True:
        return redirect(url_for('.index'))
    else:
        return x


@item_blueprint.route('/edit/<string:item_id>',methods=['GET','POST'])
@user_decorators.requires_login
def edit_item(item_id):
    item = Item.get_by_id(item_id)
    companies = Item_company.get_all_companies()
    types = Type.get_all_types()

    if request.method=='POST':
        model_name = request.form.get('model_name')
        x = request.form.get('company_name')
        company = request.form.get('add_new_company')
        hsn_code = request.form.get('hsn_code')
        type = request.form.get('add_new_type')
        y = request.form.get('type')

        tax = request.form.get('tax')
        price = request.form.get('price')
        if company == None:
            company = x
        if type == None:
            type = y
        # print(model_name,x,company,hsn_code,type,y,tax,price)
        item = Item(hsn_code, company, model_name, type, tax, price,item_id)
        item.save_to_mongo()
        return redirect(url_for('.index'))

    return render_template('items/edit_item.jinja2',item=item,companies=companies,types=types,new_item_page=True)

src/models/parties/views.py
from flask import Blueprint, request, session, url_for, render_template, jsonify
from werkzeug.utils import redirect

from src.models.invoices.invoice import Invoice
from src.models.parties.party import Party
from src.models.users.user import User
import src.models.users.errors as UserErrors


import src.models.users.decorators as user_decorators


__author__="Kunj"

party_blueprint = Blueprint('parties',__name__)

@party_blueprint.route('/')
@user_decorators.requires_login
def index():
    return render_template("party/party_list.jinja2",datatable_page=True,party_list_page=True)

@party_blueprint.route('/new_party',methods=['GET','POST'])
@user_decorators.requires_login
def new_party():
    if request.method == 'POST':
        name = request.form.get('name')
        gstin = request.form.get('gstin')
        address = request.form.get('local_address')
        state = request.form.get('state')
        country = request.form.get('country')
        pincode =request.form.get('pincode')
        contact_person_name = request.form.get('contact_person_name')
        email = request.form.get('email')
        mobile_no_1 = request.form.get('mobile_no_1')
        mobile_no_2 = request.form.get('mobile_no_2')
        city = request.form.get('city')

        party = Party(name,gstin,address,city,state,country,int(pincode),contact_person_name,mobile_no_1,email,mobile_no_2)
        party.save_to_mongo()
        #f = request.form
        #print(f)
        #for key in f.keys():
        #    for value in f.getlist(key):
        #        print(key,value)

        return redirect(url_for('.index'))

    return render_template('party/new_party.jinja2',new_party_page=True)

@party_blueprint.route('/index_get_data')
@user_decorators.requires_login
def party_data():
    #Assume data comes from somewhere else
    data = {}
    data["data"] = Party.get_data_for_list()
    return jsonify(data)

@party_blueprint.route('/delete/<string:party_id>')
@user_decorators.requires_login
def delete_party(party_id):
    x = Invoice.delete_party_possible(party_id)
    if x==True:
        return redirect(url_for('.index'))
    else:
        return x



@party_blueprint.route('/edit/<string:party_id>',methods=['GET','POST'])
@user_decorators.requires_login
def edit_party(party_id):
    if request.method == 'POST':
        name = request.form.get('name')
        gstin = request.form.get('gstin')
        address = request.form.get('local_address')
        state = request.form.get('state')
        country = request.form.get('country')
        pincode = request.form.get('pincode')
        contact_person_name = request.form.get('contact_person_name')
        email = request.form.get('email')
        mobile_no_1 = request.form.get('mobile_no_1')
        mobile_no_2 = request.form.get('mobile_no_2')
        city = request.form.get('city')
        id = party_id

        party = Party(name, gstin, address, city, state, country, int(pincode), contact_person_name, mobile_no_1, email,
                      mobile_no_2,party_id)
        party.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('party/edit_party.jinja2',new_party_page=True,party= Party.get_by_id(party_id))

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

from src.models.invoices.invoice import Invoice
from src.models.items.item import Item
from src.models.parties.party import Party
from src.models.users.Backup_restore import Backup_restore
from src.models.users.user import User
import src.models.users.errors as UserErrors
__author__="Kunj"

import src.models.users.decorators as user_decorators
user_blueprint = Blueprint('users',__name__)

@user_blueprint.route('/')
@user_decorators.requires_login
def index():
    return render_template("users/index.jinja2",index_page=True,invoices_count = Invoice.count_invoices(),items_count = Item.count_items(), parties_count = Party.count_parties())

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == "POST":
        #Check Login is valid
        email = request.form['email']
        password= request.form['password']
        try:
            if User.is_login_valid(email,password):
                session['email'] = email
                return redirect(url_for('.index'))
        except UserErrors.UserError as e:
            return e.message

    return render_template("login.jinja2") #Send the User an error is needed if login is invalid

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == "POST":
        #Check Login is valid
        email = request.form['email']
        password= request.form['password']
        username = request.form['username']
        #print(email,password)
        try:
            if User.register_user(email,password,username):
                session['email'] = email
                return "This is for admin"
        except UserErrors.UserError as e:
            return e.message
    #print(session['email'])

    return render_template("register.jinja2") #Send the User an error is needed if login is invalid
    #return "Register page"

@user_blueprint.route('/logout')
def user_logout():
    session['email']=None
    return redirect(url_for('home'))
#.home redirects in the same blueprint

@user_blueprint.route('/backup',methods=["POST"])
def database():
    action_type = request.form.get('action_type')
    date = request.form.get('date')
    #print(date,action_type)
    x = Backup_restore(date)
    if action_type == "backup":
        Backup_restore.backup()
    else:
        x.restore()
    return redirect(url_for(".index"))

src/templates/home.jinja2
<!doctype html>
<head>

    <!-- Meta tags & title /-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Easy Accounting - An Easy to Use Free Responsive WebApp</title>
    <meta name="description" content="Easy Accounting"/>
    <meta name="keywords" content="Easy, Elegant, Accounting"/>
    <meta name="Maniar Kunj" content="Web Developer">

    <!-- Favicon /-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.jpg') }}" type="image/x-icon"/>
    <!-- Favicon /-->

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

    <!-- Stylesheets /-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/gumby.css') }}">
    <!-- Gumby Framework /-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <!-- Main stylesheet /-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">            <!-- Animations /-->


    <script src="{{ url_for('static', filename='js/') }}modernizr-2.6.2.min.js"></script>  <!-- Modernizr /-->

</head>

<body>

<!-- Preload the Whole Page -->

<div id="preloader">
    <div id="loading-animation">&nbsp;</div>
</div>


<!-- NAVIGATION ############################################### -->


<div class="cbp-af-header">

    <nav>

        <!--  Share DIV-->

        <div class="right">

            <!--  Facebook Share Button-->

            <!--iframe-- src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.baribal.be%2Fshowpage%2F&amp;width&amp;layout=standard&amp;action=like&amp;show_faces=false&amp;share=true&amp;height=35"
                    scrolling="no" frameborder="0"
                    style="border:none; width:170px; height:70px; margin-right:20px;"></iframe-->

            <!-- Twitter Share Button -->

            <!--a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>-->


        </div> <!-- End Share dIV -->

        <!-- Logo -->

        <div id="logo">

            <a href="#"><img alt="Logo" src="{{ url_for('static', filename='img/logo.jpg') }}"></a>

        </div>

        <!-- Links -->

        <ul id="nav">

            <li><a href="{{ url_for('users.login_user') }}">Login</a></li>

            <!--form action="/register"-->
            <li><a href="{{ url_for('users.register_user') }}">Register</a></li>
            <!--/form-->
        </ul>

    </nav>


</div>

<!-- END NAVIGATION ############################################### -->


<!-- HEADER / FIRST SECTION ############################################### -->


<section class="page1">

    <!-- Huge Title centered -->

    <div class="huge-title centered">

        <div class="logo-phone centered"><img alt="YOURLOGO"
                                              src="{{ url_for('static', filename='img/logo-phone.png') }}">
        </div>  <!-- This Logo is only displayed on Tablet/iPhone !-->


        <h1>A Simple & Easy To Use Free App For All <br>Your Account And Bussiness Management</h1>

        <div class="space"></div>

        <a href="#container" class="button-white goto">Discover more</a>

    </div>

    <!-- IMG DISCOVER MORE -->

    <div class="go-down twelve columns">

        <a href="#container" class="goto"><img src="{{ url_for('static', filename='img/down.png') }}" alt="MORE"></a>

    </div>

</section>


<!-- END HEADER ############################################### -->


<!-- BEGIN CONTAINER ############################################### -->


<div id="container" class="container">


    <!-- SECOND SECTION ############################################### -->


    <section class="page2">

        <div class="row">

            <div class="six columns article make-it-appear-right">

                <!-- Title -->

                <h3>An Elegant Design</h3>

                <!-- Content -->

                <p>Our website plans to please the users with an awe-inspiring interface which meets all their
                    requirements at the same time.
                    It would be sleek, minimalist and optimal at the same time.
                </p>

                <div class="space"></div>

                <a href="{{ url_for('users.login_user') }}" class="js-open-modal button-blue">Login</a>


            </div>

            <!-- Image from right -->

            <div class="five columns picture make-it-appear-left">

                <img src="{{ url_for('static', filename='img/1.png') }}" alt="EXEMPLE">

            </div>

        </div> <!-- End row div -->

    </section>

    <!-- END SECOND SECTION ############################################### -->


    <!-- TIRTH SECTION ############################################### -->


    <section class="page3">

        <div class="row">

            <!-- Image from left -->

            <div class="five columns picture make-it-appear-right">

                <img src="{{ url_for('static', filename='img/2.png') }}" alt="EXEMPLE">

            </div>


            <div class="six columns article make-it-appear-left">

                <!-- Title -->

                <h3>Pretty easy to customize</h3>

                <!-- Content -->

                <p>Our website is designed in such way that it can be very easily customised and molded in such a way as
                    to suit all the requirements of the user.
                    We have a wide range of options to choose from, to change the style in which the user can design
                    their needs.</p>

                <div class="space"></div>

                <a href="{{ url_for('users.register_user') }}" class="js-open-modal button-green">Register</a>

            </div>


        </div> <!-- End row div -->
    </section>

    <!-- END TIRTH SECTION ############################################### -->


    <!-- Modal Window -->

    <div class='modal' id='modal'>

        <div class='modal-content modal-anim--three'>

            <!--iframe src="#"
                    width="560" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen
                    allowfullscreen></iframe-->

        </div>

    </div>


    <!-- FOURTH SECTION ############################################### -->


    <section class="page4">

        <div class="row">

            <div class="four columns article make-it-appear-right">

                <!-- Title -->

                <h3>Pretty Simple and Detailed Code.</h3>

                <!-- Content -->

                <p>Here is the simple exemple of the next section, as you can see, everything is pretty well detailed
                    and easy to understand.</p>

                <div class="space"></div>


            </div>

            <!-- Image -->

            <div class="seven columns picture make-it-appear-left">

<pre>
		    	<!-- Article centered on the Page -->

				<div class="twelve columns centered make-it-appear-top">

					<!-- Title -->

					<h4>Finally! Simple and fair pricing.</h4>

                    <!-- Content -->


					<div class="cost">
						<p class="symbol">₹</p>
						<p class="value">0</p>
					</div>


				</div>
</pre>

            </div>

        </div> <!-- End row div -->

    </section>


    <!-- END FOURTH SECTION ############################################### -->


    <!-- FIFTH SECTION ############################################### -->


    <section class="page5">


        <div class="row">

            <!-- Article centered on the Page -->

            <div class="twelve columns centered make-it-appear-top">

                <!-- Title -->

                <h4>Finally! Simple and fair pricing.</h4>

                <!-- Content -->

                <h1>₹1000</h1>


            </div>


        </div>


    </section>


    <!-- END FIFTH SECTION ############################################### -->


    <!-- FOOTER SECTION ############################################### -->


    <section class="footer">


        <div class="row">

            <!-- Article centered on the Page -->

            <div class="nine columns centered">

                <!-- Nav Footer -->

                <ul>
                    <!--<li><a href="http://www.iamsupview.be">About Supview</a> </li>
                    <li> <a href="http://www.baribal.be/showpage/dl/">Get it</a> </li>
                    <li> <a href="http://dribbble.com/Supview">Dribbble</a> </li-->
                    <li><a href="#" rel="nofollow">Facebook</a></li>
                    <!--li> <a href="http://twitter.com/Supview" rel="nofollow">Twitter</a> </li>
                    <li> <a href="http://www.behance.net/Supview" rel="nofollow">Behance</a> </li>
                </ul>

                <!-- Title -->


                    <p class="copyright">Easy Accounting is a free app landing website and is under CC License <br>©
                        Copyright 2019 Easy Accounting. All rights reserved.</p>

                    <!-- Logo -->


                    <img class="logo" src="{{ url_for('static', filename='img/logo.jpg') }}" alt="Logo">

            </div>


        </div>


    </section>


    <!-- END FOOTER SECTION ############################################### -->


</div> <!-- end of container -->


<!-- Grab Google CDN's jQuery, fall back to local if offline -->
<!--script-- src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script-->
<script src="{{ url_for('static', filename='js/jquery-1.9.1.min.js') }}" type="text/javascript"></script>

<script src="{{ url_for('static', filename='js/main.js') }}" type="text/javascript"></script>
<!-- Main Javascript File -->
<script src="{{ url_for('static', filename='js/classie.js') }}" type="text/javascript"></script>
<!-- Scroll from left & right -->
<script src="{{ url_for('static', filename='js/waypoints.min.js') }}" type="text/javascript"></script>
<!-- Waypoints -->
<script src="{{ url_for('static', filename='js/jquery.scrollto.js') }}" type="text/javascript"></script>
<!-- ScrollTo -->
<script src="{{ url_for('static', filename='js/mediaCheck.js') }}" type="text/javascript"></script>
<!-- MediaCheck -->


</body>

</html>

src/templates/sidebar.jinja2
<div class="d-flex align-items-stretch">
      <!-- Sidebar Navigation-->
      <nav id="sidebar">
        <!-- Sidebar Header-->
        <div class="sidebar-header d-flex align-items-center">
          <div class="avatar"><img src="{{url_for('static', filename='img/avatar-6.jpg')}}" alt="..." class="img-fluid rounded-circle"></div>
          <div class="title">
            <h1 class="h5">Maniar Kunj</h1>
            <p>Software Designer</p>
          </div>
        </div>
        <!-- Sidebar Navidation Menus-->
        <span class="heading">Main</span>
        <ul class="list-unstyled">
          <li> <a href="{{ url_for('users.index') }}" class="{{ '' if not index_page else 'color_expan' }}"> <i class="icon-home"></i>Home</a></li>
        </ul>
        <!--ul class="list-unstyled">
          <li> <a href="{{ url_for('companies.index') }}" class="{{ '' if not company_page else 'color_expan' }}"> <i class="icon-presentation"></i>Company</a></li>
        </ul-->
          <ul class="list-unstyled ">
                <li>
                <a href="#exampledropdownDropdown2" data-toggle="collapse" aria-expanded="false">
                <i class="icon-padnote"></i>Companies</a>
                <ul id="exampledropdownDropdown2" class="collapse list-unstyled ">
                    <li><a href="/companies/new">Create</a></li>
                    <li><a href="/company/list">List</a></li>
                </ul>
            </li>
          </ul>
        <ul class="list-unstyled">
          <li data-toggle="modal" data-target="#database"> <a href="#"> <i class="icon-cloud"></i>Database</a></li>
        </ul>
        <span class="heading">Masters</span>
        <ul class="list-unstyled">
         <!--\ <li class="active"><a href="index.html"> <i class="icon-home"></i>Home </a></li>
          <li><a href="tables.html"> <i class="icon-grid"></i>Tables </a></li>
          <li><a href="charts.html"> <i class="fa fa-bar-chart"></i>Charts </a></li>
          <li><a href="forms.html"> <i class="icon-padnote"></i>Forms </a></li>-->

            <li><a href="#exampledropdownDropdown0" aria-expanded="{{ 'false' if not (new_item_page or item_list_page) else 'true'}}" data-toggle="collapse" >
          	<i class="icon-padnote"></i>Items</a>
            <ul id="exampledropdownDropdown0" class="{{ 'collapse' if not (new_item_page or item_list_page) else '' }} list-unstyled ">
				<li><a href="{{ url_for('items.new_item') }}"  class={{ '' if not new_item_page else 'color_expan' }}>Create</a></li>
                <li><a href="{{ url_for('items.index') }}" class="{{ '' if not item_list_page else 'color_expan ' }}">List</a></li>
            </ul>
        </li>
            <li><a href="#exampledropdownDropdown1" data-toggle="collapse" aria-expanded="{{ 'false' if not (new_party_page or party_list_page) else 'true'}}">
          	<i class="icon-padnote"></i>Party</a>
            <ul id="exampledropdownDropdown1" class="{{ 'collapse' if not (new_party_page or party_list_page)else '' }} list-unstyled ">
				<li><a href="{{ url_for('parties.new_party') }}" class={{ '' if not new_party_page else 'color_expan' }}>Create</a></li>
                <li><a href="{{ url_for('parties.index') }}" class="{{ '' if not party_list_page else 'color_expan' }}">List</a></li>
            </ul>
       </li>


          <!--li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse" >
          	<i class="icon-windows"></i>Accounts Information </a>
            <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
				<li><a href="#exampledropdownDropdown1" aria-expanded="false" data-toggle="collapse">Ledgers</a>
              		<ul id="exampledropdownDropdown1" class="collapse list-unstyled ">
              			<li><a href="{{'/account_info/ledgers/create'}}">Create</a></li>
              			<li><a href="#">Display</a></li>
              			<li><a href="#">Alter</a></li>
              		</ul>
				</li>
              <li><a href="#exampledropdownDropdown2" aria-expanded="false" data-toggle="collapse">Groups</a>
              		<ul id="exampledropdownDropdown2" class="collapse list-unstyled ">
              			<li><a href="{{'/account_info/groups/create'}}">Create</a></li>
              			<li><a href="{{'/account_info/groups/display'}}">Display</a></li>
              			<li><a href="{{'/account_info/groups/create'}}">Alter</a></li>
              		</ul>
              </li>
              <li><a href="#exampledropdownDropdown3" aria-expanded="false" data-toggle="collapse">Voucher Types</a>
              <ul id="exampledropdownDropdown3" class="collapse list-unstyled ">
              			<li><a href="#">Create</a></li>
              			<li><a href="#">Display</a></li>
              			<li><a href="#">Alter</a></li>
              		</ul>
              	</li>
            </ul>
          </li>
          <li><a href="#exampledropdownDropdown4" aria-expanded="false" data-toggle="collapse">
          	<i class="icon-windows"></i>Inventory Information </a>
            <ul id="exampledropdownDropdown4" class="collapse list-unstyled ">
				<li><a href="#exampledropdownDropdown5" aria-expanded="false" data-toggle="collapse">Stock Groups</a>
              		<ul id="exampledropdownDropdown5" class="collapse list-unstyled ">
              			<li><a href="{{'/inventory_info/stock_group/create'}}">Create</a></li>
              			<li><a href="#">Alter</a></li>
              			<li><a href="#">Delete</a></li>
              		</ul>
				</li>
              <li><a href="#exampledropdownDropdown6" aria-expanded="false" data-toggle="collapse">Stock Items</a>
              <ul id="exampledropdownDropdown6" class="collapse list-unstyled ">
              			<li><a href="{{'/inventory_info/stock_item/create'}}">Create</a></li>
              			<li><a href="#">Display</a></li>
              			<li><a href="#">Alter</a></li>
              		</ul>
              	</li>
              <li><a href="#exampledropdownDropdown7" aria-expanded="false" data-toggle="collapse">Units of Measurement</a>
              	<ul id="exampledropdownDropdown7" class="collapse list-unstyled ">
              			<li><a href="{{'/inventory_info/stock_unit/create'}}">Create</a></li>
              			<li><a href="#">Display</a></li>
              			<li><a href="#">Alter</a></li>
              		</ul>
              </li>
              <li><a href="#exampledropdownDropdown8" aria-expanded="false" data-toggle="collapse">Voucher Types</a>
              	<ul id="exampledropdownDropdown8" class="collapse list-unstyled ">
              			<li><a href="#">Create</a></li>
              			<li><a href="#">Display</a></li>
              			<li><a href="#">Alter</a></li>
              		</ul>
              </li>
              <li><a href="#exampledropdownDropdown9" aria-expanded="false" data-toggle="collapse">Tax Rate Setup</a>
              	<ul id="exampledropdownDropdown9" class="collapse list-unstyled ">
              			<li><a href="#">GST</a></li>
              		</ul>
              </li>
            </ul>
          </li-->
         <!-- <li><a href="login.html"> <i class="icon-logout"></i>Login page </a></li>>
        </ul>
<span class="heading">Invoice</span>
        <ul-- class="list-unstyled">
          <li><a href="#exampledropdownDropdown10" aria-expanded="false" data-toggle="collapse" >
          	<i class="icon-padnote"></i>Sales Invoice</a>
            <ul id="exampledropdownDropdown10" class="collapse list-unstyled ">
				<li><a href="#">Create</a></li>
				<li><a href="#">List</a></li>
            </ul>
        </li>
          <li><a href="#exampledropdownDropdown11" aria-expanded="false" data-toggle="collapse" >
          	<i class="icon-padnote"></i>Inventory Vouchers</a>
            <ul id="exampledropdownDropdown11" class="collapse list-unstyled ">
				<li><a href="#">Physical Stock Verification</a></li>
				<li><a href="#">Material In and Material Out</a></li>
				<li><a href="#">Delivery Note and Receipt Note</a></li>
            </ul>
        </li>
        <li><a href="#exampledropdownDropdown12" aria-expanded="false" data-toggle="collapse" >
          	<i class="icon-padnote"></i>Order Vouchers</a>
            <ul id="exampledropdownDropdown12" class="collapse list-unstyled ">
				<li><a href="#">Purchase Order and Sales Order</a></li>
            </ul>
        </li>
        </ul-->
        <span class="heading" style="margin-top: 15px;">Invoice</span>
        <ul class="list-unstyled">
          <li class={{ '' if not new_invoice_page else 'color_expan2' }}> <a href="{{ url_for('invoices.new_invoice') }}" class={{ '' if not new_invoice_page else 'color_expan2' }}> <i class="icon-chart"></i>Create</a></li>
          <li class={{ '' if not invoice_list_page else 'color_expan2' }}> <a href="{{ url_for('invoices.index') }}"> <i class="icon-chart"></i>List </a></li>
          <li class={{ '' if not serial_no_list_page else 'color_expan2' }}> <a href="{{ url_for('invoices.serial_no_datatable') }}"> <i class="icon-chart"></i>Serial No. List</a></li>
            <!--li> <a href="#"> <i class="icon-chart"></i>Stock Summary </a></li>
          <li> <a href="#"> <i class="icon-chart"></i>Ratio Analysis </a></li-->
        </ul>
        </ul>
      </nav>
      <!-- Sidebar Navigation end-->