src/models/invoices/views.py
import datetime

from flask import Blueprint, request, session, url_for, render_template,jsonify
from werkzeug.utils import redirect

from src.models.companies.company import Company
from src.models.invoices.excel_sheet_maker import Excel_export
from src.models.invoices.invoice import Invoice
from src.models.invoices.invoice_item import Invoice_item
from src.models.invoices.serial_no import Serial_no
from src.models.items.item import Item
from src.common.utils1 import Utils
import src.models.users.decorators as user_decorators
from src.models.items.type import Type
from src.models.parties.party import Party

__author__="Kunj"

invoice_blueprint = Blueprint('invoices',__name__)


@invoice_blueprint.route('/')
@user_decorators.requires_login
def index():
    return render_template('invoices/invoice_list.jinja2',datatable_page=True,invoice_list_page=True)

@invoice_blueprint.route('/new',methods=['GET','POST'])
@user_decorators.requires_login
def new_invoice():
    print(session['email'])
    if request.method=='POST':
        string={}
        data = request.form
        print(data)
        print()
        for key in data.keys():
            for value in data.getlist(key):
                string[key]=value
        # ---- Invoice Creation ----

        no = string['number']
        party_id = Party.get_by_gstin(string['select_party'])

        date = string['date']
        narration = string['narration']

        invoice_amount=string['total_amount']
        e_way = string['e_way']

        invoice = Invoice(no,party_id._id,invoice_amount,date,narration,e_way)
        invoice.save_to_mongo()
        s = invoice._id
        print('invoice_id',s)
        # --- Find Items
        items = []
        serial_no = {}

        for i in string:
            print(i[:7])
            if i[:12] == 'select_item_':
                items.append([i, string[i][14::]])

            if i[:7] == 'myModal':
                if i[8] != '_':
                    num = int(i[7]) * 10 + int(i[8])
                else:
                    num = int(i[7])
                if str(num) not in serial_no:
                    serial_no[str(num)] = []

                serial_no[str(num)].append(string[i])

        #print(items)
        item_details = []
        for i in range(len(items)):
            item = items[i][0][12::]
            quantity = string['quantity_' + item]
            rate_per = string['rate_per_' + item]
            item_details.append([item,items[i][1], quantity, rate_per, serial_no[item]])

        #print()
        #print(item_details)

        for i in item_details:
            item_id = Item.get_by_name(i[1])
            print(invoice._id,item_id,float(i[3]),int(i[2]))
            invoice_item = Invoice_item(invoice._id,item_id._id,float(i[3]),int(i[2]))
            invoice_item.save_to_mongo()
            for j in i[4]:
                serial_no = Serial_no(invoice_item._id,j)
                serial_no.save_to_mongo()
        #print()
        #print(serial_no)
        #print(string)

        return redirect(url_for('.print_invoice',invoice_id=s))

    parties = Party.get_parties()
    items = Item.get_items()
    return render_template('invoices/new_invoice.jinja2',new_invoice_page=True,parties=parties,items=items,company=Company.get_company()[0])


@invoice_blueprint.route('/delete/<string:invoice_id>')
@user_decorators.requires_login
def delete_invoice(invoice_id):
    Invoice.get_by_id(invoice_id).delete()
    return redirect(url_for('.index'))


@invoice_blueprint.route('/edit/<string:invoice_id>',methods=['GET','POST'])
@user_decorators.requires_login
def edit_invoice(invoice_id):
    parties = Party.get_parties()
    items = Item.get_items()
    invoice_items = Invoice_item.get_by_invoice_id(invoice_id)

    company = Company.get_company()
    invoice = Invoice.get_by_id(invoice_id)
    invoice.date = datetime.datetime.strftime(invoice.date, "%d-%m-%Y")
    invoice_package = {}
    invoice_package['invoice'] = invoice

    party = Party.get_by_id(invoice.party_id)

    invoice_package['party'] = party
    tax_type = party.tax_type()
    tax, igst, round_off, total_amount, hsn_taxable_tot, total_quantity = 0.0, 0.0, 0.0, 0.0, 0.0, 0

    invoice_package['invoice_items'] = []
    sr = 0

    for invoice_item in invoice_items:
        sr += 1
        serial_no = Serial_no.get_by_invoice_item_id(invoice_item._id)
        total_quantity += invoice_item.quantity
        item = Item.get_by_id(invoice_item.item_id)
        amount_item = int(invoice_item.quantity) * float(invoice_item.rate_per)
        if tax_type == "gst":
            tax1 = amount_item * float(item.tax) / 200
            total_amount += (tax1 * 2)
        else:
            tax1 = amount_item * float(item.tax) / 100
            total_amount += tax1
        tax += tax1
        hsn_taxable_tot += amount_item
        invoice_package['invoice_items'].append({
            "invoice_item": invoice_item,
            "item": item,
            "serial_no": serial_no,
            "amount": amount_item,
            "sr_no": sr
        })

    if tax_type == "gst":
        x = tax * 2
    else:
        x = tax
    invoice_package['total_tax_amount'] = x
    total = hsn_taxable_tot + x
    round_off = abs(round(total) - total)
    invoice_package['tax'] = tax
    invoice_package['total_items'] = len(invoice_items)
    invoice_package['round_off'] = round_off
    invoice_package['total'] = total
    invoice_package['tax_type'] = tax_type
    invoice_package['company'] = company[0]

    #    for i in invoice_package:
    #        print(i,invoice_package[i])

    if request.method == 'POST':
        Invoice.get_by_id(invoice_id).delete()
        string = {}
        data = request.form
        print(data)
        print()
        for key in data.keys():
            for value in data.getlist(key):
                string[key] = value

        for i in string:
            print(i,string[i])
        # ---- Invoice Creation ----

        no = string['number']
        party_id = Party.get_by_gstin(string['select_party'])

        date = string['date']
        narration = string['narration']

        invoice_amount = string['total_amount']
        e_way = string['e_way']

        invoice = Invoice(no, party_id._id, invoice_amount, date, narration,e_way)
        invoice.save_to_mongo()
        # --- Find Items
        items = []
        serial_no = {}

        for i in string:
            print(i[:7])
            if i[:12] == 'select_item_':
                items.append([i, string[i][14::]])

            if i[:7] == 'myModal':
                if i[8] != '_':
                    num = int(i[7]) * 10 + int(i[8])
                else:
                    num = int(i[7])
                if str(num) not in serial_no:
                    serial_no[str(num)] = []

                serial_no[str(num)].append(string[i])

        # print(items)
        item_details = []
        for i in range(len(items)):
            item = items[i][0][12::]
            quantity = string['quantity_' + item]
            rate_per = string['rate_per_' + item]
            item_details.append([item, items[i][1], quantity, rate_per, serial_no[item]])

        # print()
        # print(item_details)

        for i in item_details:
            item_id = Item.get_by_name(i[1])
            print(invoice._id, item_id, float(i[3]), int(i[2]))
            invoice_item = Invoice_item(invoice._id, item_id._id, float(i[3]), int(i[2]))
            invoice_item.save_to_mongo()
            for j in i[4]:
                serial_no = Serial_no(invoice_item._id, j)
                serial_no.save_to_mongo()
        # print()
        # print(serial_no)
        # print(string)

        return redirect(url_for('.print_invoice', invoice_id=invoice._id))

    return render_template('invoices/edit_invoice.jinja2',invoice_package=invoice_package,edit_invoice_page=True,parties=parties,items=items,company=Company.get_company()[0])





@invoice_blueprint.route('/print/<string:invoice_id>',methods=['POST','GET'])
@user_decorators.requires_login
def print_invoice(invoice_id):
    print(invoice_id)
    company = Company.get_company()
    company[0].address = format(company[0].address)
    company[0].address=Utils.format_address(company[0].address)

    invoice = Invoice.get_by_id(invoice_id)

    if(invoice is None):
        invoice = Invoice.get_by_no(invoice_id)
    invoice_id = invoice._id
    invoice.date = datetime.datetime.strftime(invoice.date,"%d-%m-%Y")
    invoice_items = Invoice_item.get_by_invoice_id(invoice_id)
    invoice_package = {}
    invoice_package['invoice'] = invoice
    #invoice_package.append(invoice)
    party = Party.get_by_id(invoice.party_id)
    party.address = Utils.format_address(party.address)
    invoice_package['party'] = party
    tax_type = party.tax_type()
    tax, igst, round_off, total_amount, hsn_taxable_tot, total_quantity = 0.0, 0.0, 0.0, 0.0, 0.0,0
    hsn_list = {}

    invoice_package['invoice_items'] = []
    sr=0
    for invoice_item in invoice_items:
        sr+=1
        serial_no = Serial_no.get_by_invoice_item_id(invoice_item._id)
        total_quantity += invoice_item.quantity
        #invoice_package.append([invoice_item,serial_no])

        item = Item.get_by_id(invoice_item.item_id)
        print(item.type_id)
        amount_item = int(invoice_item.quantity)*float(invoice_item.rate_per)

        if item.hsn not in hsn_list:
            hsn_list[item.hsn] = [0,invoice_item.rate_per,0,0,item.tax]

        if tax_type == "gst":
            tax1 = amount_item*float(item.tax)/200
            total_amount+=(tax1*2)
        else:
            tax1 = amount_item*float(item.tax)/100
            total_amount+=tax1

        hsn_list[item.hsn][2] += tax1
        hsn_list[item.hsn][0]+=amount_item

        if tax_type=="gst":
            hsn_list[item.hsn][3] += tax1*2
        else:
            hsn_list[item.hsn][3] += tax1
        hsn_taxable_tot +=amount_item
        tax += tax1

src/models/items/views.py
from flask import Blueprint, request, render_template, jsonify, redirect, url_for, session

from src.models.invoices.invoice import Invoice
from src.models.items.item_company import Item_company
from src.models.items.item import Item
from src.models.items.type import Type

import src.models.users.decorators as user_decorators


__author__="Kunj"

item_blueprint = Blueprint('items',__name__)

@item_blueprint.route('/')
@user_decorators.requires_login
def index():
    print(session)
    return render_template("items/item_list.jinja2",datatable_page=True,item_list_page=True)

@item_blueprint.route('/new',methods=['POST', 'GET'])
@user_decorators.requires_login
def new_item():
    if request.method == 'POST':
        print("POST")
        model_name = request.form.get('model_name')
        x = request.form.get('company_name')
        company = request.form.get('add_new_company')
        hsn_code = request.form.get('hsn_code')
        type = request.form.get('add_new_type')
        y = request.form.get('type')

        tax = request.form.get('tax')
        price = request.form.get('price')
        if company == None:
            company = x
        if type == None:
            type = y
        #print(model_name,x,company,hsn_code,type,y,tax,price)
        item = Item(hsn_code,company,model_name,type,tax,price)
        item.save_to_mongo()
        return redirect(url_for('.index'))
        #return render_template("KK")
    companies = Item_company.get_all_companies()
    types = Type.get_all_types()
    return render_template('items/new_item.jinja2',companies=companies,types=types,new_item_page=True)


@item_blueprint.route('/index_get_data')
@user_decorators.requires_login
def item_data():
    #Assume data comes from somewhere else
    data = {}
    data["data"] = Item.get_data_for_list()
    return jsonify(data)

@item_blueprint.route('/delete/<string:item_id>')
@user_decorators.requires_login
def delete_item(item_id):
    x = Invoice.delete_item_possible(item_id)
    if x==True:
        return redirect(url_for('.index'))
    else:
        return x


@item_blueprint.route('/edit/<string:item_id>',methods=['GET','POST'])
@user_decorators.requires_login
def edit_item(item_id):
    item = Item.get_by_id(item_id)
    companies = Item_company.get_all_companies()
    types = Type.get_all_types()

    if request.method=='POST':
        model_name = request.form.get('model_name')
        x = request.form.get('company_name')
        company = request.form.get('add_new_company')
        hsn_code = request.form.get('hsn_code')
        type = request.form.get('add_new_type')
        y = request.form.get('type')

        tax = request.form.get('tax')
        price = request.form.get('price')
        if company == None:
            company = x
        if type == None:
            type = y
        # print(model_name,x,company,hsn_code,type,y,tax,price)
        item = Item(hsn_code, company, model_name, type, tax, price,item_id)
        item.save_to_mongo()
        return redirect(url_for('.index'))

    return render_template('items/edit_item.jinja2',item=item,companies=companies,types=types,new_item_page=True)

src/models/parties/views.py
from flask import Blueprint, request, session, url_for, render_template, jsonify
from werkzeug.utils import redirect

from src.models.invoices.invoice import Invoice
from src.models.parties.party import Party
from src.models.users.user import User
import src.models.users.errors as UserErrors


import src.models.users.decorators as user_decorators


__author__="Kunj"

party_blueprint = Blueprint('parties',__name__)

@party_blueprint.route('/')
@user_decorators.requires_login
def index():
    return render_template("party/party_list.jinja2",datatable_page=True,party_list_page=True)

@party_blueprint.route('/new_party',methods=['GET','POST'])
@user_decorators.requires_login
def new_party():
    if request.method == 'POST':
        name = request.form.get('name')
        gstin = request.form.get('gstin')
        address = request.form.get('local_address')
        state = request.form.get('state')
        country = request.form.get('country')
        pincode =request.form.get('pincode')
        contact_person_name = request.form.get('contact_person_name')
        email = request.form.get('email')
        mobile_no_1 = request.form.get('mobile_no_1')
        mobile_no_2 = request.form.get('mobile_no_2')
        city = request.form.get('city')

        party = Party(name,gstin,address,city,state,country,int(pincode),contact_person_name,mobile_no_1,email,mobile_no_2)
        party.save_to_mongo()
        #f = request.form
        #print(f)
        #for key in f.keys():
        #    for value in f.getlist(key):
        #        print(key,value)

        return redirect(url_for('.index'))

    return render_template('party/new_party.jinja2',new_party_page=True)

@party_blueprint.route('/index_get_data')
@user_decorators.requires_login
def party_data():
    #Assume data comes from somewhere else
    data = {}
    data["data"] = Party.get_data_for_list()
    return jsonify(data)

@party_blueprint.route('/delete/<string:party_id>')
@user_decorators.requires_login
def delete_party(party_id):
    x = Invoice.delete_party_possible(party_id)
    if x==True:
        return redirect(url_for('.index'))
    else:
        return x



@party_blueprint.route('/edit/<string:party_id>',methods=['GET','POST'])
@user_decorators.requires_login
def edit_party(party_id):
    if request.method == 'POST':
        name = request.form.get('name')
        gstin = request.form.get('gstin')
        address = request.form.get('local_address')
        state = request.form.get('state')
        country = request.form.get('country')
        pincode = request.form.get('pincode')
        contact_person_name = request.form.get('contact_person_name')
        email = request.form.get('email')
        mobile_no_1 = request.form.get('mobile_no_1')
        mobile_no_2 = request.form.get('mobile_no_2')
        city = request.form.get('city')
        id = party_id

        party = Party(name, gstin, address, city, state, country, int(pincode), contact_person_name, mobile_no_1, email,
                      mobile_no_2,party_id)
        party.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('party/edit_party.jinja2',new_party_page=True,party= Party.get_by_id(party_id))

src/templates/users/index.jinja2
{% extends "statics.jinja2" %}
{% include "header.jinja2" %}
{% include "sidebar.jinja2" %}
{% block content %}

<div class="page-content">
        <div class="page-header">
          <div class="container-fluid">
            <h2 class="h5 no-margin-bottom">Hello {{ session['email'] }}<br>Dashboard</h2>
          </div>
        </div>
        <section class="no-padding-top no-padding-bottom">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-4 col-sm-6">
                <div class="statistic-block block">
                  <div class="progress-details d-flex align-items-end justify-content-between">
                    <div class="title">
                      <div class="icon"><i class="icon-user-1"></i></div><strong><a href="{{ url_for('items.index') }}">Items</a></strong>
                    </div>
                    <div class="number dashtext-1">{{ items_count }}</div>
                  </div>
                  <div class="progress progress-template">
                    <div role="progressbar" style="width: {{ items_count/1000 }}%" aria-valuenow="{{ items_count }}" aria-valuemin="0" aria-valuemax="1000" class="progress-bar progress-bar-template dashbg-1"></div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-sm-6">
                <div class="statistic-block block">
                  <div class="progress-details d-flex align-items-end justify-content-between">
                    <div class="title">
                        <div class="icon"><i class="icon-contract"></i></div><strong><a href="{{ url_for('parties.index') }}">Parties</a></strong>
                    </div>
                    <div class="number dashtext-2">{{ parties_count }}</div>
                  </div>
                  <div class="progress progress-template">
                    <div role="progressbar" style="width: {{ parties_count/2000 }}%" aria-valuenow="{{ parties_count }}" aria-valuemin="0" aria-valuemax="2000" class="progress-bar progress-bar-template dashbg-2"></div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-sm-6">
                <div class="statistic-block block">
                  <div class="progress-details d-flex align-items-end justify-content-between">
                    <div class="title">
                        <div class="icon"><i class="icon-paper-and-pencil"></i></div><strong><a href="{{ url_for('invoices.index') }}">Invoices</a></strong>
                    </div>
                    <div class="number dashtext-3">{{ invoices_count }}</div>
                  </div>
                  <div class="progress progress-template">
                    <div role="progressbar" style="width: {{ invoices_count/10000 }}%" aria-valuenow="{{ invoices_count }}" aria-valuemin="0" aria-valuemax="10000" class="progress-bar progress-bar-template dashbg-3"></div>
                  </div>
                </div>
              </div>
              <!--div class="col-md-3 col-sm-6">
                <div class="statistic-block block">
                  <div class="progress-details d-flex align-items-end justify-content-between">
                    <div class="title">
                      <div class="icon"><i class="icon-writing-whiteboard"></i></div><strong>Reports</strong>
                    </div>
                    <div class="number dashtext-4">41</div>
                  </div>
                  <div class="progress progress-template">
                    <div role="progressbar" style="width: 35%" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100" class="progress-bar progress-bar-template dashbg-4"></div>
                  </div>
                </div>
              </div-->
            </div>
          </div>
        </section>






    <section class="margin-bottom-sm">
          <div class="container-fluid">
            <div class="row d-flex align-items-stretch">
              <div class="col-lg-4">
                <div class="stats-with-chart-1 block">
                  <div class="title"> <strong class="d-block">Sales Difference</strong><span class="d-block">Lorem ipsum dolor sit</span></div>
                  <div class="row d-flex align-items-end justify-content-between">
                    <div class="col-5">
                      <div class="text"><strong class="d-block dashtext-3">₹740</strong><span class="d-block">May 2017</span><small class="d-block">320 Sales</small></div>
                    </div>
                    <div class="col-7">
                      <div class="bar-chart chart">
                        <canvas id="salesBarChart1"></canvas>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="stats-with-chart-1 block">
                  <div class="title"> <strong class="d-block">Visit Statistics</strong><span class="d-block">Lorem ipsum dolor sit</span></div>
                  <div class="row d-flex align-items-end justify-content-between">
                    <div class="col-4">
                      <div class="text"><strong class="d-block dashtext-1">₹457</strong><span class="d-block">May 2017</span><small class="d-block">210 Sales</small></div>
                    </div>
                    <div class="col-8">
                      <div class="bar-chart chart">
                        <canvas id="visitPieChart"></canvas>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="stats-with-chart-1 block">
                  <div class="title"> <strong class="d-block">Sales Activities</strong><span class="d-block">Lorem ipsum dolor sit</span></div>
                  <div class="row d-flex align-items-end justify-content-between">
                    <div class="col-5">
                      <div class="text"><strong class="d-block dashtext-2">80%</strong><span class="d-block">May 2017</span><small class="d-block">+35 Sales</small></div>
                    </div>
                    <div class="col-7">
                      <div class="bar-chart chart">
                        <canvas id="salesBarChart2"></canvas>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="no-padding-bottom">
        </section>




    <section>
          <div class="container-fluid">
            <div class="row">
              <div class="col-lg-4">
                <div class="stats-with-chart-2 block">
                  <div class="title"><strong class="d-block">Credit Sales</strong><span class="d-block"></span></div>
                  <div class="piechart chart">
                    <canvas id="pieChartHome1"></canvas>
                    <div class="text"><strong class="d-block">₹2.145</strong><span class="d-block">Sales</span></div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="stats-with-chart-2 block">
                  <div class="title"><strong class="d-block">Channel Sales</strong><span class="d-block"></span></div>
                  <div class="piechart chart">
                    <canvas id="pieChartHome2"></canvas>
                    <div class="text"><strong class="d-block">₹7.784</strong><span class="d-block">Sales</span></div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="stats-with-chart-2 block">
                  <div class="title"><strong class="d-block">Direct Sales</strong><span class="d-block"></span></div>
                  <div class="piechart chart">
                    <canvas id="pieChartHome3"></canvas>
                    <div class="text"><strong class="d-block">₹4.957</strong><span class="d-block">Sales</span></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

{% endblock %}