src/models/items/views.py
from flask import Blueprint, request, render_template, jsonify, redirect, url_for, session

from src.models.invoices.invoice import Invoice
from src.models.items.item_company import Item_company
from src.models.items.item import Item
from src.models.items.type import Type

import src.models.users.decorators as user_decorators


__author__="Kunj"

item_blueprint = Blueprint('items',__name__)

@item_blueprint.route('/')
@user_decorators.requires_login
def index():
    print(session)
    return render_template("items/item_list.jinja2",datatable_page=True,item_list_page=True)

@item_blueprint.route('/new',methods=['POST', 'GET'])
@user_decorators.requires_login
def new_item():
    if request.method == 'POST':
        print("POST")
        model_name = request.form.get('model_name')
        x = request.form.get('company_name')
        company = request.form.get('add_new_company')
        hsn_code = request.form.get('hsn_code')
        type = request.form.get('add_new_type')
        y = request.form.get('type')

        tax = request.form.get('tax')
        price = request.form.get('price')
        if company == None:
            company = x
        if type == None:
            type = y
        #print(model_name,x,company,hsn_code,type,y,tax,price)
        item = Item(hsn_code,company,model_name,type,tax,price)
        item.save_to_mongo()
        return redirect(url_for('.index'))
        #return render_template("KK")
    companies = Item_company.get_all_companies()
    types = Type.get_all_types()
    return render_template('items/new_item.jinja2',companies=companies,types=types,new_item_page=True)


@item_blueprint.route('/index_get_data')
@user_decorators.requires_login
def item_data():
    #Assume data comes from somewhere else
    data = {}
    data["data"] = Item.get_data_for_list()
    return jsonify(data)

@item_blueprint.route('/delete/<string:item_id>')
@user_decorators.requires_login
def delete_item(item_id):
    x = Invoice.delete_item_possible(item_id)
    if x==True:
        return redirect(url_for('.index'))
    else:
        return x


@item_blueprint.route('/edit/<string:item_id>',methods=['GET','POST'])
@user_decorators.requires_login
def edit_item(item_id):
    item = Item.get_by_id(item_id)
    companies = Item_company.get_all_companies()
    types = Type.get_all_types()

    if request.method=='POST':
        model_name = request.form.get('model_name')
        x = request.form.get('company_name')
        company = request.form.get('add_new_company')
        hsn_code = request.form.get('hsn_code')
        type = request.form.get('add_new_type')
        y = request.form.get('type')

        tax = request.form.get('tax')
        price = request.form.get('price')
        if company == None:
            company = x
        if type == None:
            type = y
        # print(model_name,x,company,hsn_code,type,y,tax,price)
        item = Item(hsn_code, company, model_name, type, tax, price,item_id)
        item.save_to_mongo()
        return redirect(url_for('.index'))

    return render_template('items/edit_item.jinja2',item=item,companies=companies,types=types,new_item_page=True)

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

from src.models.invoices.invoice import Invoice
from src.models.items.item import Item
from src.models.parties.party import Party
from src.models.users.Backup_restore import Backup_restore
from src.models.users.user import User
import src.models.users.errors as UserErrors
__author__="Kunj"

import src.models.users.decorators as user_decorators
user_blueprint = Blueprint('users',__name__)

@user_blueprint.route('/')
@user_decorators.requires_login
def index():
    return render_template("users/index.jinja2",index_page=True,invoices_count = Invoice.count_invoices(),items_count = Item.count_items(), parties_count = Party.count_parties())

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == "POST":
        #Check Login is valid
        email = request.form['email']
        password= request.form['password']
        try:
            if User.is_login_valid(email,password):
                session['email'] = email
                return redirect(url_for('.index'))
        except UserErrors.UserError as e:
            return e.message

    return render_template("login.jinja2") #Send the User an error is needed if login is invalid

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == "POST":
        #Check Login is valid
        email = request.form['email']
        password= request.form['password']
        username = request.form['username']
        #print(email,password)
        try:
            if User.register_user(email,password,username):
                session['email'] = email
                return "This is for admin"
        except UserErrors.UserError as e:
            return e.message
    #print(session['email'])

    return render_template("register.jinja2") #Send the User an error is needed if login is invalid
    #return "Register page"

@user_blueprint.route('/logout')
def user_logout():
    session['email']=None
    return redirect(url_for('home'))
#.home redirects in the same blueprint

@user_blueprint.route('/backup',methods=["POST"])
def database():
    action_type = request.form.get('action_type')
    date = request.form.get('date')
    #print(date,action_type)
    x = Backup_restore(date)
    if action_type == "backup":
        Backup_restore.backup()
    else:
        x.restore()
    return redirect(url_for(".index"))

src/templates/items/edit_item.jinja2
{% extends "statics.jinja2" %}
{% include "header.jinja2" %}

{% include "sidebar.jinja2" %}
{% block content %}
    <div class="page-content">
        <!-- Page Header-->
        <div class="page-header no-margin-bottom">
            <div class="container-fluid">
                <h2 class="h5 no-margin-bottom">Item Creation</h2>
            </div>
        </div>
        <!-- Breadcrumb-->

        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('users.index') }}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ url_for('items.index') }}">Items</a></li>
                <li class="breadcrumb-item active">Edit Item</li>
            </ul>
        </div>
        <section class="no-padding-top">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="block">
                            <div class="title"><strong>Basic Details</strong></div>
                            <div class="block-body">
                                <form method="post" class="form-horizontal">
                                    <div class="form-group row margin-row">
                                        <label for="model_name" class="col-sm-3 form-control-label">Model Name</label>
                                        <div class="col-sm-9">
                                            <input required id="model_name" name="model_name" type="text" class="form-control" value="{{ item.model_name }}">
                                        </div>
                                    </div>
                                    <div class="line"></div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">Company Name</label>
                                        <div class="col-sm-2">
                                            <div class="i-checks">
                                                <input id="new_company_check" type="checkbox" value=""
                                                       class="new_check new_company_check checkbox-template">
                                                <label for="new_company_check">Add New</label>
                                            </div>
                                        </div>
                                        <div class="col-sm-7 div_select new_company_check" id="div_select_company">
                                            <select id="company_name" name="company_name"
                                                    class="select_id new_company_check form-control mb-3 mb-3 selectpicker"
                                                    data-live-search="true" title="Select Company" required>
                                                {% for company in companies %}
                                                    <option value={{ company.name }} data-token={{ company.name }} {% if company._id==item.company_id %}{{ 'selected' }}{% endif %}>{{ company.name }}</option>
                                                {% endfor %}
                                                <!--option data-token="option 1">option 1</option>
                                                <option data-token="option 1">option 2</option>
                                                <option data-token="option 1">option 3</option>
                                                <option data-token="option 1">option 4</option-->
                                            </select>
                                            <!--small class="help-block-none">Select from alredy Added</small-->
                                        </div>
                                        <!--label class="col-sm-2 form-control-label">AddCompany name Name</label-->
                                        <div id="add_company" class="div_add col-sm-7 new_company_check">
                                            <input id="add_new_company" name="add_new_company" placeholder="Add New Company" type="text"
                                                   class="add_new form-control new_company_check" required>
                                            <!--small class="help-block-none">Add New Company</small-->
                                        </div>
                                    </div>
                                    <div class="line"></div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">HSN Code</label>
                                        <div class="col-sm-9">
                                            <input id="hsn_code" name="hsn_code" type="text" class="form-control" value="{{ item.hsn }}" required>
                                        </div>
                                    </div>


                                    <div class="line"></div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">Item Type</label>
                                        <div class="col-sm-2">
                                            <div class="i-checks">
                                                <input id="new_item_check" name="new_item_check" type="checkbox" value=""
                                                       class="new_check checkbox-template">
                                                <label for="new_item_check">Add New</label>
                                            </div>
                                        </div>
                                        <div class="col-sm-7 div_select new_item_check" id="div_select_company">
                                            <select id="type" name="type"
                                                    class="select_id form-control mb-3 mb-3 selectpicker new_item_check"
                                                    data-live-search="true" required>
                                                {% for type in types %}
                                                <option value={{ type.type_name }} data-token={{ type.type_name }} {% if type._id==item.type_id %}{{ 'selected' }}{% endif %}>{{ type.type_name }}</option>
                                                {% endfor %}
                                                <!--option data-token="option 1">option 2</option>
                                                <option data-token="option 1">option 3</option>
                                                <option data-token="option 1">option 4</option-->
                                            </select>
                                            <!--small class="help-block-none">Select from alredy Added</small-->
                                        </div>
                                        <!--label class="col-sm-2 form-control-label">AddCompany name Name</label-->
                                        <div id="add_company" class="div_add col-sm-7 new_item_check">
                                            <input required id="add_new_type" name="add_new_type" type="text" placeholder="Add new type" class="add_new form-control new_item_check">
                                            <!--small class="help-block-none">Add New Item</small-->
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">Tax</label>
                                        <div class="col-sm-9">
                                            <div class="row">
                                                <div class="col-md-2">
                                                    <input id="tax" name="tax" type="text" placeholder="%" class="form-control" value="{{ item.tax }}">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">Price</label>
                                        <div class="col-sm-9">
                                            <div class="row">
                                                <div class="col-md-2">
                                                    <input id="price" name="price" type="text" placeholder="Amount" class="form-control" value="{{ item.price }}" required>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="line"></div>
                                    <div class="form-group row">
                                        <div class="col-sm-9 ml-auto">
                                            <button type="button" class="btn btn-secondary">Cancel</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

src/templates/items/item_list.jinja2
{% extends "statics.jinja2" %}
{% include "header.jinja2" %}
{% include "sidebar.jinja2" %}

{% block content %}

     <div class="page-content">
        <!-- Page Header-->
        <div class="page-header no-margin-bottom">
          <div class="container-fluid">
            <h2 class="h5 no-margin-bottom">Tables</h2>
          </div>
        </div>
        <!-- Breadcrumb-->
        <div class="container-fluid">
          <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('users.index') }}">Home</a></li>
            <li class="breadcrumb-item active">Items</li>
          </ul>
        </div>
         <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header" style="display: flow-root; align-items: flex-start;-ms-flex-pack: justify;justify-content: space-between;padding: 1rem 1rem;border-bottom: 1px solid #e9ecef;border-bottom-color: rgb(233, 236, 239);border-top-left-radius: .3rem;border-top-right-radius: .3rem;">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
                </div>

                <div class="modal-body">
                    <p>You are about to delete one track, this procedure is irreversible.</p>
                    <p>Do you want to proceed?</p>
                    <p id="debug-url"></p>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger btn-ok">Delete</a>
                </div>
            </div>
        </div>
    </div>
        <section class="no-padding-top">
          <div class="container-fluid">
            <div class="row">
              <div class="col-lg-12">
                <div class="block margin-bottom-sm">
                  <div class="title"><strong>Basic Table</strong>
                      </div>

                    <div class="table-responsive">

                    <table id="item" class="display table table-hover">
                      <thead>
                        <tr>
                          <th>Model Name</th>
                          <th>Company</th>
                          <th>HSN Code</th>
                          <th>Item Type</th>
                          <th>Tax</th>
                          <th>Price</th>
                            <th>Actions</th>
                        </tr>
                      </thead>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>


{% endblock %}

src/templates/items/new_item.jinja2
{% extends "statics.jinja2" %}
{% include "header.jinja2" %}

{% include "sidebar.jinja2" %}
{% block content %}
    <div class="page-content">
        <!-- Page Header-->
        <div class="page-header no-margin-bottom">
            <div class="container-fluid">
                <h2 class="h5 no-margin-bottom">Item Creation</h2>
            </div>
        </div>
        <!-- Breadcrumb-->

        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('users.index') }}">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Items</a></li>
                <li class="breadcrumb-item active"><a href="#">New Item</a></li>
            </ul>
        </div>
        <section class="no-padding-top">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="block">
                            <div class="title"><strong>Basic Details</strong></div>
                            <div class="block-body">
                                <form method="post" class="form-horizontal" action="{{ url_for('items.new_item') }}">
                                    <div class="form-group row margin-row">
                                        <label for="model_name" class="col-sm-3 form-control-label">Model Name</label>
                                        <div class="col-sm-9">
                                            <input id="model_name" name="model_name" type="text" class="form-control" required>
                                        </div>
                                    </div>
                                    <div class="line"></div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">Company Name</label>
                                        <div class="col-sm-2">
                                            <div class="i-checks">
                                                <input id="new_company_check" type="checkbox" value=""
                                                       class="new_check new_company_check checkbox-template">
                                                <label for="new_company_check">Add New</label>
                                            </div>
                                        </div>
                                        <div class="col-sm-7 div_select new_company_check" id="div_select_company">
                                            <select id="company_name" name="company_name"
                                                    class="select_id new_company_check form-control mb-3 mb-3 selectpicker"
                                                    data-live-search="true" title="Select Company" required>
                                                <option value="" disabled selected data-token="option 1">Select Company</option>
                                                {% for company in companies %}
                                                    <option value={{ company.name }} data-token={{ company.name }}>{{ company.name }}</option>
                                                {% endfor %}
                                                <!--option data-token="option 1">option 1</option>
                                                <option data-token="option 1">option 2</option>
                                                <option data-token="option 1">option 3</option>
                                                <option data-token="option 1">option 4</option-->
                                            </select>
                                            <!--small class="help-block-none">Select from alredy Added</small-->
                                        </div>
                                        <!--label class="col-sm-2 form-control-label">AddCompany name Name</label-->
                                        <div id="add_company" class="div_add col-sm-7 new_company_check">
                                            <input id="add_new_company" name="add_new_company" placeholder="Add New Company" type="text"
                                                   class="add_new form-control new_company_check" required>
                                            <!--small class="help-block-none">Add New Company</small-->
                                        </div>
                                    </div>
                                    <div class="line"></div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">HSN Code</label>
                                        <div class="col-sm-9">
                                            <input id="hsn_code" name="hsn_code" type="text" class="form-control" required>
                                        </div>
                                    </div>


                                    <div class="line"></div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">Item Type</label>
                                        <div class="col-sm-2">
                                            <div class="i-checks">
                                                <input id="new_item_check" name="new_item_check" type="checkbox" value=""
                                                       class="new_check checkbox-template">
                                                <label for="new_item_check">Add New</label>
                                            </div>
                                        </div>
                                        <div class="col-sm-7 div_select new_item_check" id="div_select_company">
                                            <select id="type" name="type"
                                                    class="select_id form-control mb-3 mb-3 selectpicker new_item_check"
                                                    data-live-search="true" required>
                                                <option value="0" disabled selected data-token="option 1">Select Type
                                                </option>
                                                {% for type in types %}
                                                <option value={{ type.type_name }} data-token={{ type.type_name }}>{{ type.type_name }}</option>
                                                {% endfor %}
                                                <!--option data-token="option 1">option 2</option>
                                                <option data-token="option 1">option 3</option>
                                                <option data-token="option 1">option 4</option-->
                                            </select>
                                            <!--small class="help-block-none">Select from alredy Added</small-->
                                        </div>
                                        <!--label class="col-sm-2 form-control-label">AddCompany name Name</label-->
                                        <div id="add_company" class="div_add col-sm-7 new_item_check">
                                            <input id="add_new_type" name="add_new_type" required type="text" placeholder="Add new type" class="add_new form-control new_item_check">
                                            <!--small class="help-block-none">Add New Item</small-->
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">Tax</label>
                                        <div class="col-sm-9">
                                            <div class="row">
                                                <div class="col-md-2">
                                                    <input id="tax" name="tax" type="text" required placeholder="%" class="form-control">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label">Price</label>
                                        <div class="col-sm-9">
                                            <div class="row">
                                                <div class="col-md-2">
                                                    <input id="price" name="price" type="text" required placeholder="Amount" class="form-control">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="line"></div>
                                    <div class="form-group row">
                                        <div class="col-sm-9 ml-auto">
                                            <button type="" class="btn btn-secondary">Cancel</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}